### ISSUE TITLE
King can be taken like a normal piece without check or checkmate

### ISSUE THREAD

**Issue by mdg1317** [malikh22/ShogiCS301#3]
Component: Game rules
Severity: Major

To recreate:
In the current state, since any piece can move anywhere, tap any of your pieces on the board and then tap the king. The king can be taken without check or checkmate, and the game over message will be displayed.

**Comment by malikh22** [comment]
As of now, this is now intentional, since a player is not allowed to make moves that would put them into check (based on the rules of Shogi), so there never really will be a "check" state, you will have to actually capture the king to end the game. However, I will be adding some sort of dialog box to address this.

**Comment by malikh22** [comment]
The real problem here was the illegal movement. Otherwise, we have decided that the most graceful way to end the game is with the capture of one of the kings.

**Comment by mdg1317** [comment]
If the king being taken to end the game while in checkmate is intentional as you mentioned above, then the illegal movement has been fixed
